AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  refreshrepositoriologslambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::597495568095:role/service-role/refresh-repositorio-logs-lambda-role-7xiezubz
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
